//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    using System.Drawing;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Bitmap _null
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("null", Resources.resourceCulture);
            }
        }

        // Token: 0x17000079 RID: 121
        // (get) Token: 0x060002CF RID: 719 RVA: 0x000047E9 File Offset: 0x000029E9
        internal static string AssemblyRandom
        {
            get
            {
                return Resources.ResourceManager.GetString("AssemblyRandom", Resources.resourceCulture);
            }
        }

        // Token: 0x1700007A RID: 122
        // (get) Token: 0x060002D0 RID: 720 RVA: 0x000047FF File Offset: 0x000029FF
        internal static byte[] Aut2exe
        {
            get
            {
                return (byte[])Resources.ResourceManager.GetObject("Aut2exe", Resources.resourceCulture);
            }
        }

        // Token: 0x1700007B RID: 123
        // (get) Token: 0x060002D1 RID: 721 RVA: 0x0000481A File Offset: 0x00002A1A
        internal static Bitmap back_481
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("back_481", Resources.resourceCulture);
            }
        }

        // Token: 0x1700007C RID: 124
        // (get) Token: 0x060002D2 RID: 722 RVA: 0x00004835 File Offset: 0x00002A35
        internal static Bitmap ca77749
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("ca77749", Resources.resourceCulture);
            }
        }

        // Token: 0x1700007D RID: 125
        // (get) Token: 0x060002D3 RID: 723 RVA: 0x00004850 File Offset: 0x00002A50
        internal static Bitmap can749
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("can749", Resources.resourceCulture);
            }
        }

        // Token: 0x1700007E RID: 126
        // (get) Token: 0x060002D4 RID: 724 RVA: 0x0000486B File Offset: 0x00002A6B
        internal static Bitmap code_
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("code_", Resources.resourceCulture);
            }
        }

        // Token: 0x1700007F RID: 127
        // (get) Token: 0x060002D5 RID: 725 RVA: 0x00004886 File Offset: 0x00002A86
        internal static Bitmap code__
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("code__", Resources.resourceCulture);
            }
        }

        // Token: 0x17000080 RID: 128
        // (get) Token: 0x060002D6 RID: 726 RVA: 0x000048A1 File Offset: 0x00002AA1
        internal static Bitmap Crypt_
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("Crypt_", Resources.resourceCulture);
            }
        }

        // Token: 0x17000081 RID: 129
        // (get) Token: 0x060002D7 RID: 727 RVA: 0x000048BC File Offset: 0x00002ABC
        internal static Bitmap CS_Icon_Terms_And_Conditions
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("CS_Icon_Terms_And_Conditions", Resources.resourceCulture);
            }
        }

        // Token: 0x17000082 RID: 130
        // (get) Token: 0x060002D8 RID: 728 RVA: 0x000048D7 File Offset: 0x00002AD7
        internal static Bitmap forward_48
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("forward-48", Resources.resourceCulture);
            }
        }

        // Token: 0x17000083 RID: 131
        // (get) Token: 0x060002D9 RID: 729 RVA: 0x000048F2 File Offset: 0x00002AF2
        internal static Bitmap help_
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("help_", Resources.resourceCulture);
            }
        }

        // Token: 0x17000084 RID: 132
        // (get) Token: 0x060002DA RID: 730 RVA: 0x0000490D File Offset: 0x00002B0D
        internal static Bitmap help__
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("help__", Resources.resourceCulture);
            }
        }

        // Token: 0x17000085 RID: 133
        // (get) Token: 0x060002DB RID: 731 RVA: 0x00004928 File Offset: 0x00002B28
        internal static Bitmap help___
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("help___", Resources.resourceCulture);
            }
        }

        // Token: 0x17000086 RID: 134
        // (get) Token: 0x060002DC RID: 732 RVA: 0x00004943 File Offset: 0x00002B43
        internal static Bitmap Home_
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("Home_", Resources.resourceCulture);
            }
        }

        // Token: 0x17000087 RID: 135
        // (get) Token: 0x060002DD RID: 733 RVA: 0x0000495E File Offset: 0x00002B5E
        internal static Bitmap Home__
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("Home__", Resources.resourceCulture);
            }
        }

        // Token: 0x17000088 RID: 136
        // (get) Token: 0x060002DE RID: 734 RVA: 0x00004979 File Offset: 0x00002B79
        internal static Bitmap Home___
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("Home___", Resources.resourceCulture);
            }
        }

        // Token: 0x17000089 RID: 137
        // (get) Token: 0x060002DF RID: 735 RVA: 0x00004994 File Offset: 0x00002B94
        internal static Bitmap Home___1
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("Home___1", Resources.resourceCulture);
            }
        }

        // Token: 0x1700008A RID: 138
        // (get) Token: 0x060002E0 RID: 736 RVA: 0x000049AF File Offset: 0x00002BAF
        internal static Bitmap icondisplay
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("icondisplay", Resources.resourceCulture);
            }
        }

        // Token: 0x1700008B RID: 139
        // (get) Token: 0x060002E1 RID: 737 RVA: 0x000049CA File Offset: 0x00002BCA
        internal static byte[] load
        {
            get
            {
                return (byte[])Resources.ResourceManager.GetObject("load", Resources.resourceCulture);
            }
        }

        // Token: 0x1700008C RID: 140
        // (get) Token: 0x060002E2 RID: 738 RVA: 0x000049E5 File Offset: 0x00002BE5
        internal static Bitmap R
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("R", Resources.resourceCulture);
            }
        }

        // Token: 0x1700008D RID: 141
        // (get) Token: 0x060002E3 RID: 739 RVA: 0x00004A00 File Offset: 0x00002C00
        internal static byte[] res
        {
            get
            {
                return (byte[])Resources.ResourceManager.GetObject("res", Resources.resourceCulture);
            }
        }

        // Token: 0x1700008E RID: 142
        // (get) Token: 0x060002E4 RID: 740 RVA: 0x00004A1B File Offset: 0x00002C1B
        internal static Bitmap Scan_
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("Scan_", Resources.resourceCulture);
            }
        }

        // Token: 0x1700008F RID: 143
        // (get) Token: 0x060002E5 RID: 741 RVA: 0x00004A36 File Offset: 0x00002C36
        internal static Bitmap search
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("search", Resources.resourceCulture);
            }
        }

        // Token: 0x17000090 RID: 144
        // (get) Token: 0x060002E6 RID: 742 RVA: 0x00004A51 File Offset: 0x00002C51
        internal static byte[] StaticNETPack
        {
            get
            {
                return (byte[])Resources.ResourceManager.GetObject("StaticNETPack", Resources.resourceCulture);
            }
        }

        // Token: 0x17000091 RID: 145
        // (get) Token: 0x060002E7 RID: 743 RVA: 0x00004A6C File Offset: 0x00002C6C
        internal static string String1
        {
            get
            {
                return Resources.ResourceManager.GetString("String1", Resources.resourceCulture);
            }
        }

        // Token: 0x17000092 RID: 146
        // (get) Token: 0x060002E8 RID: 744 RVA: 0x00004A82 File Offset: 0x00002C82
        internal static string String10
        {
            get
            {
                return Resources.ResourceManager.GetString("String10", Resources.resourceCulture);
            }
        }

        // Token: 0x17000093 RID: 147
        // (get) Token: 0x060002E9 RID: 745 RVA: 0x00004A98 File Offset: 0x00002C98
        internal static string String11
        {
            get
            {
                return Resources.ResourceManager.GetString("String11", Resources.resourceCulture);
            }
        }

        // Token: 0x17000094 RID: 148
        // (get) Token: 0x060002EA RID: 746 RVA: 0x00004AAE File Offset: 0x00002CAE
        internal static string String12
        {
            get
            {
                return Resources.ResourceManager.GetString("String12", Resources.resourceCulture);
            }
        }

        // Token: 0x17000095 RID: 149
        // (get) Token: 0x060002EB RID: 747 RVA: 0x00004AC4 File Offset: 0x00002CC4
        internal static string String2
        {
            get
            {
                return Resources.ResourceManager.GetString("String2", Resources.resourceCulture);
            }
        }

        // Token: 0x17000096 RID: 150
        // (get) Token: 0x060002EC RID: 748 RVA: 0x00004ADA File Offset: 0x00002CDA
        internal static string String3
        {
            get
            {
                return Resources.ResourceManager.GetString("String3", Resources.resourceCulture);
            }
        }

        // Token: 0x17000097 RID: 151
        // (get) Token: 0x060002ED RID: 749 RVA: 0x00004AF0 File Offset: 0x00002CF0
        internal static string String4
        {
            get
            {
                return Resources.ResourceManager.GetString("String4", Resources.resourceCulture);
            }
        }

        // Token: 0x17000098 RID: 152
        // (get) Token: 0x060002EE RID: 750 RVA: 0x00004B06 File Offset: 0x00002D06
        internal static string String5
        {
            get
            {
                return Resources.ResourceManager.GetString("String5", Resources.resourceCulture);
            }
        }

        // Token: 0x17000099 RID: 153
        // (get) Token: 0x060002EF RID: 751 RVA: 0x00004B1C File Offset: 0x00002D1C
        internal static string String6
        {
            get
            {
                return Resources.ResourceManager.GetString("String6", Resources.resourceCulture);
            }
        }

        // Token: 0x1700009A RID: 154
        // (get) Token: 0x060002F0 RID: 752 RVA: 0x00004B32 File Offset: 0x00002D32
        internal static string String7
        {
            get
            {
                return Resources.ResourceManager.GetString("String7", Resources.resourceCulture);
            }
        }

        // Token: 0x1700009B RID: 155
        // (get) Token: 0x060002F1 RID: 753 RVA: 0x00004B48 File Offset: 0x00002D48
        internal static string String8
        {
            get
            {
                return Resources.ResourceManager.GetString("String8", Resources.resourceCulture);
            }
        }

        // Token: 0x1700009C RID: 156
        // (get) Token: 0x060002F2 RID: 754 RVA: 0x00004B5E File Offset: 0x00002D5E
        internal static string String9
        {
            get
            {
                return Resources.ResourceManager.GetString("String9", Resources.resourceCulture);
            }
        }

        // Token: 0x1700009D RID: 157
        // (get) Token: 0x060002F3 RID: 755 RVA: 0x00004B74 File Offset: 0x00002D74
        internal static byte[] upx
        {
            get
            {
                return (byte[])Resources.ResourceManager.GetObject("upx", Resources.resourceCulture);
            }
        }

        // Token: 0x1700009E RID: 158
        // (get) Token: 0x060002F4 RID: 756 RVA: 0x00004B8F File Offset: 0x00002D8F
        internal static Bitmap user_128
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("user-128", Resources.resourceCulture);
            }
        }

        // Token: 0x1700009F RID: 159
        // (get) Token: 0x060002F5 RID: 757 RVA: 0x00004BAA File Offset: 0x00002DAA
        internal static Bitmap user_icollppn
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("user-icollppn", Resources.resourceCulture);
            }
        }

        // Token: 0x170000A0 RID: 160
        // (get) Token: 0x060002F6 RID: 758 RVA: 0x00004BC5 File Offset: 0x00002DC5
        internal static Bitmap user_icon
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("user-icon", Resources.resourceCulture);
            }
        }

        // Token: 0x170000A1 RID: 161
        // (get) Token: 0x060002F7 RID: 759 RVA: 0x00004BE0 File Offset: 0x00002DE0
        internal static Bitmap user_icondd
        {
            get
            {
                return (Bitmap)Resources.ResourceManager.GetObject("user-icondd", Resources.resourceCulture);
            }
        }
    }
}
